name: Compress Images

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'

  pull_request:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
  workflow_dispatch:

jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: calibreapp/image-actions
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: calibreapp/image-actions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}