name: Push to Staging Repo

on:
    push:
        branches: [staging]
    workflow_dispatch:

jobs:
    DeployToStaging:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Push to Staging Repo
              run: |
                  git remote add staging https://mathnauleau:${{ secrets.GH_PAT }}@github.com/mathnauleau/staging-repo.git
                  git push --force staging staging:gh-pages