name: Compress Images

on:
  pull_request:
    paths:
      - 'static/**'

jobs:
  compress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ secrets.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 }}
      - uses: namoscato/action-tinify@v1
        with:
          api_key: ${{ secrets.b0ZTrhb0g5M9QX4wf6TWKQGCq4XZsMkK }}